[[week7]]
[preface]
= Week 7 Midterm Presentation Schedule

This week we are dividing the class into three groups to present midterm projects.  You are welcome to attend more than just your group session of course.  If your assigned time does not work for you, please let me know.  If for some reason, you cannot present next week, let me know and we'll make alternate arrangements.

Presentations will be approximately 8 minutes each.

[[week5_video9]]
[role="shoutout"]
.Midterm Documentation Links
****
Please post a link to your midterm documentation here.  Your documentation should include something visual (screen capture, video documentation, or running JS sketch) as well as documentation of your source code.  
****


==== Group 1: 9:30 - 11:00
* Maria Paula
* Matt E
* Gal / Talya
* Katie
* Mike A
* Bill
* GJ
* Su
* Louise
* Archana

==== Group 2: 11:30 - 1:00
* Tarana
* David
* Michelle
* Colin
* Nadine
* Vanessa
* Monica
* Lei
* Asli
* Sam
* Ju

==== Group 3: 1:30 - 3:00
* Matt L
* Melissa
* Jorge
* Peiqi
* Maxim
* Lilia
* Rose
* Sonia
* Luca 
* Youjin
