[[week8]]
= Nature of Code: Week 8

This week in order to get to the material faster than I am producing the videos, I am covering the material in class.  Following is a list of links from our discussions today.  If I've missed anything, please let me know.

== http://natureofcode.com/book/chapter-6-autonomous-agents/[Session 1: Chapter 6 Autonomous Agents] (videos coming soon)
* https://vimeo.com/22955812[Casey Reas Process Compendium]
* http://books.google.com/books/about/Vehicles.html?id=7KkUAT_q_sQC[Vehicles: Experiments in Synthetic Psychology by Valentino Braitenberg]
* http://www.red3d.com/cwr/steer/[Craig Reynolds' Steering]
* http://www.nytimes.com/2007/11/13/science/13traff.html?_r=1&oref=slogin[From Ants to People, an instinct to Swarm]

== http://natureofcode.com/book/chapter-7-cellular-automata[Session 2: Chapter 7 Cellular Automata] (videos coming soon)
* http://www.wolframscience.com/[Wolfram's A New Kind of Science]
* http://www.ibiblio.org/lifepatterns/october1970.html[Game of Life original scientific american article]
* https://github.com/stevenklise/ConwaysGameOfLife[Steve Klise's GOL processing.js implementation]
* http://llk.media.mit.edu/projects/emergence/[Exploring Emergence]

== http://natureofcode.com/book/chapter-8-fractals[Session 3: Chapter 9 Fractals] (videos coming soon)
* http://www.pbs.org/wgbh/nova/physics/hunting-hidden-dimension.html[Nova: Hunting the Hidden Dimension], http://www.youtube.com/watch?v=LemPnZn54Kw[Youtube Link]
* http://en.wikipedia.org/wiki/How_Long_Is_the_Coast_of_Britain%3F_Statistical_Self-Similarity_and_Fractional_Dimension[How Long is the Coastline of Britain by Benoit Mandelbrot]
* http://algorithmicbotany.org/papers/#abop[The Algorithmic Beauty of Plants] (for more about L-Systems)

[[week8_homework]]
[preface]
== Homework Week 8

For the remainder of this semester you should be working on your final project.  We'll do this in three stages.

1. Final Project Experimentation -- Create several quick and dirty sketches that implement the beginnings or seeds of an idea.
2. Final Project Proposal -- develop a more thought of plan and proposal.
3. Final Project -- Build the final project and present in class!

For your week 8 homework, do #1 above.  If you are stuck for an idea, here are some suggestions for exercises that might lead you towards an idea from the material in chapters 6-8.

* Steering Behaviors
** Implement seeking a moving target, often referred to as “pursuit.“  In this case, your desired velocity won't point towards the object's current location, rather its “future“ location as extrapolated based on its current velocity.
** Create a sketch where a Vehicle's maximum force and maximum speed do not remain constant, but rather vary according to environmental factors.
** Create a flow field that changes over time
** Create a flow field based on image data
** Expand the path following example to have a path that changes over time.  Can the points that define the path itself have their own steering behaviors?
** Create something inspired by Braitenberg's Vehicles
* Flocking
** Implement Flake's "View" rule, described in Computational Beauty of Nature
** Create a flocking simulation where all of the parameters (separation weight, cohesion weight, alignment weight, maximum force, maximum speed) change over time.  They could be controlled by Perlin noise or by user interaction.
** Build a creature with countless steering behaviors (as many as you can reasonably add).  Think about ways to vary the weights of these behaviors so that you can dial those behaviors up and down, mixing and matching on the fly.    How are creatures' initial weights set?  What rules drive how the weights change over time?
** Use applyForce() in Box2D or addForce() in Toxiclibs to create a flocking simulation in one of those physics engines
** Complex systems can be nested.  Can you design a single creature out of a flock of boids?  And can you then make a flock of those creatures?
* Cellular Automata
** Combine CA with the flocking example -- what happens if you assign each boid a "state" which influences its behavior?
** Consider the state of a cell to be its color.  What types of image processing filters can you create using the principles of Cellular Automata?
** Develop your own rules for a Cellular Automata, 1D or 2D.   This could be something completely made up or a simulation of real-world phenomena.  For example, forest fires: [http://en.wikipedia.org/wiki/Forest-fire_model[http://en.wikipedia.org/wiki/Forest-fire_model]] or Predator, Prey [p. 191 of Computational Beauty of Nature.]
** Develop an alternative "Game of Life" with time as factor, i.e. what does it mean for a cell to be "alive" or "dead" for many frames in a row.
* Fractals
** Build a fractal structure with physics.  For each with make a fractal tree where branch of the tree is two toxiclibs particles connected with a spring. How can you get the tree to stand up and not fall down?
** Use an L-system as a set of instructions for creating objects stored in an ArrayList. Use trigonometry and vector math to perform the rotations instead of matrix transformations (much like in the Koch curve example).

[[homework_week8_links]]
[role="shoutout"]
.Post your homework
****
Post a link to your homework assignment here.
****

