[[week3]]
= Nature of Code: Week 3

Topics for this week include:

* <<week3_angles,Angles and Angular Motion>>
* <<week3_trig, Trigonometry and Polar Coordinates>>
* <<week3_wave, Simple Harmonic Motion>>
* <<week3_pendulum, Case Study: Pendulum>>
* <<week3_spring, Case Study: Spring>>

[[week3_angles]]
[preface]
== Angles and Angular Motion

video::http://player.vimeo.com/video/59509643[height='300', width='500', poster='generic_video.png']

[[week3_video1]]
[role="shoutout"]
.Confused by this video?
****
Post any questions or comments here.
****

* Read along in the http://natureofcode.com/book/chapter-3-oscillation/[Nature of Code Chapter 3: Oscillation]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_01_angular_motion[Example 3.1: Angular Motion]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_02_forces_angular_motion[Example 3.2: Angular Motion for Moving Body]


[[week3_trig]]
[preface]
== Trigonometry and Polar Coordinates

video::http://player.vimeo.com/video/59509645[height='300', width='500', poster='generic_video.png']

[[week3_video2]]
[role="shoutout"]
.Confused by this video?
****
Post any questions or comments here.
****

* Read along in the http://natureofcode.com/book/chapter-3-oscillation/[Nature of Code Chapter 3: Oscillation]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_01_angular_motion[Example 3.1: Angular Motion]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_02_forces_angular_motion[Example 3.2: Angular Motion for Moving Body]

[[week3_wave]]
[preface]
== Simple Harmonic Motion

video::http://player.vimeo.com/video/59509644[height='300', width='500', poster='generic_video.png']

[[week3_video3]]
[role="shoutout"]
.Confused by this video?
****
Post any questions or comments here.
****

* Read along in: http://natureofcode.com/book/chapter-3-oscillation/#chapter03_section6[Nature of Code Chapter 3: Oscillation]

* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_05_simple_harmonic_motion[Example 3.5: Simple Harmonic Motion I]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_06_simple_harmonic_motion[Example 3.6: Simple Harmonic Motion II]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_07_oscillating_objects[Example 3.7: Oscillating Objects]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_08_static_wave_lines[Example 3.8: Waves]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/NOC_3_09_exercise_additive_wave[Example 3.9: Additive Waves]
* https://github.com/shiffman/The-Nature-of-Code-Examples/tree/master/Processing/chp3_oscillation/AttractionArrayWithOscillation[Extra: Moving bodies with oscillating motion]

[[week3_pendulum]]
[preface]
== Pendulums

* Video coming soon
* Read along in: http://natureofcode.com/book/chapter-3-oscillation/#chapter03_section9[Nature of Code Chapter 3.9: Pendulums]


[[week3_spring]]
[preface]
== Springs

* Video coming soon
* Read along in: http://natureofcode.com/book/chapter-3-oscillation/#chapter03_section9[Nature of Code Chapter 3.10: Springs]

[[week3_homework]]
[preface]
== Homework Week 3

Incorporate oscillatory motion into a previous assignment (or create a new one).  Some suggestions:

* Rewrite the above Oscillator class so that each object doesn't simply oscillate around the middle of the Processing window (width/2,height/2), but around a moving point.  In other words, design a creature that moves around the screen according to location, velocity, and acceleration.  But that creature isn't just a static shape, it's an oscillating body.  Consider tying the speed of oscillation to the speed of motion.  Think of a butterfly's flapping wings or the legs of an insect.  Can you make it appear that the creature's internal mechanics (oscillation) drive its locomotion?  (See "AttractionArrayWithOscillation" example as a model). 

* Create a simulation where objects are shot out of a cannon.  Each object should experience a sudden force when shot (just once) as well as gravity (always present).   Add rotation to the object to model its spin as its shot from the cannon.  How realistic can you make it look?

* Create a simulation of a vehicle that you can drive around the screen using the arrow keys: left arrow accelerates the car to the left, right to the right.  The car should point in the direction it is currently moving.

* Simulate the spaceship in the game Asteroids.   In case you aren't familiar with Asteroids, here is a brief description.   A spaceship (represented as a triangle) floats in two dimensional space.   The left arrow keys turns the spaceship counter-clockwise, the right clock-wise.  The space bar applies a “thrust“ force in the direction the spaceship is pointing.   See "_03_asteroids" example for sample answer.

* String together a series of pendulums so that the endpoint of one is the origin point of another.

* Use trigonometry to model a box sliding down an incline with friction.  Note that the magnitude of the friction force is equal to the normal force. 

* Rework the wave examples to have a Wave class and visualize the wave using something other than circles. http://www.shiffman.net/itp/classes/nature/week04_s09/OOPWave.zip[Example Answer (minus the change in visualization)]

* Using the Spring example as a basis, create a system of multiple bobs and spring connections.  How would you have a Bob connected to a Bob with no fixed anchor?

* Research and implement a simulation of http://en.wikipedia.org/wiki/Torque[Torque].

As always, please create a web page to document your homework. Make sure it include some visual documentation of your work as well as the source code.

[[homework_week3_links]]
[role="shoutout"]
.Post your homework
****
Post a link to your homework assignment here.
****

[preface]
== Supplemental Reading

* http://natureofcode.com/book/chapter-3-oscillation[The Nature of Code Chapter 3: Oscillation]
* The Mathematics of Oscillatory Motion (refer to e-mail to class list.)
* http://www.phy6.org/stargaze/Strig1.htm[Trigonometry, What is it good for?] (follow along to 7 parts)
* http://www.amazon.com/gp/product/1584503300/[Mathematics and Physics for Programmers], Chapter 4, Danny Kodicek   

